# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96947864cf26136eb6ea568e9c174fdc9594163662b66456f324676909adb68d7bf504b1d63162ca4de5f4b85072b1a4c7aaffa0d6abe91a5cec47db7b26f38

test:
  secret_key_base: a3edfbce4eaef98e38bedb618ab1e8cb7de5cef8fe18da4308de30e63ab723f0eff950da4bc6c48e793f0ad8c46c043a6d4382d68bab79fd0de793aa6b65743f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
